### 회원가입
POST http://localhost:8080/api/users
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="test.png"
Content-Type: image/png

< ./test.png
--WebAppBoundary
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "email": "email_c166bd3665aa",
  "phoneNumber": "phoneNumber_a461870f84fb",
  "street": "street_f42fa85a43a1",
  "zipCode": "zipCode_3f828ede8a5d",
  "state": "state_b33630e89d76",
  "city": "city_6232d43546ca",
  "details": "details_2de90f41ec58",
  "name": "name_435c00db2258",
  "nickname": "nickname_9ca5bcb1ad24"
}

> {%
    client.global.set("id", response.body.data.userId);
%}

### 회원 정보 조회
GET localhost:8080/api/users/{{id}}

> {%
    client.global.set("currentNickname", response.body.nickname);
    client.global.set("currentPhoneNumber", String(response.body.phoneNumber));
    client.global.set("currentStreet", response.body.street);
    client.global.set("currentZipCode", response.body.zipCode);
    client.global.set("currentState", response.body.state);
    client.global.set("currentCity", response.body.city);
    client.global.set("currentDetails", response.body.details);
    client.global.set("currentImageId", response.body.imageId);
%}



### 회원가입 프로필 이미지 null일 경우
POST http://localhost:8080/api/users
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="test.png"
Content-Type: image/png

--WebAppBoundary
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "email": "eail_c166bd3665aa",
  "phoneNumber": "poneNumber_a461870f84fb",
  "street": "streetf42fa85a43a1",
  "zipCode": "zipCde_3f828ede8a5d",
  "state": "stateb33630e89d76",
  "city": "city_232d43546ca",
  "details": "dtails_2de90f41ec58",
  "name": "name435c00db2258",
  "nickname": "nicame_9ca5bcb1ad24"
}

> {%
    client.global.set("id", response.body.data.userId);
%}

### 회원 정보 수정 (전체)
PATCH http://localhost:8080/api/users/{{id}}
Content-Type: application/json

{
  "nickname": "updated_nickname",
  "phoneNumber": "010-0000-0000",
  "street": "updated_street",
  "city": "updated_city",
  "state": "updated_state",
  "details": "updated_details",
  "zipCode": "updated_zipCode"
}

### 회원 정보 수정 (닉네임)
PATCH http://localhost:8080/api/users/{{id}}
Content-Type: application/json

{
  "nickname": "new_nickname",
  "phoneNumber": "{{currentPhoneNumber}}",
  "street": "{{currentStreet}}",
  "city": "{{currentCity}}",
  "state": "{{currentState}}",
  "details": "{{currentDetails}}",
  "zipCode": "{{currentZipCode}}"
}

### 회원 정보 수정 (연락처)
PATCH http://localhost:8080/api/users/{{id}}
Content-Type: application/json

{
   "nickname": "{{currentNickname}}",
  "phoneNumber": "010-1111-1111",
  "street": "{{currentStreet}}",
  "city": "{{currentCity}}",
  "state": "{{currentState}}",
  "details": "{{currentDetails}}",
  "zipCode": "{{currentZipCode}}"
}

### 회원 정보 수정 (주소 - 도로명)
PATCH http://localhost:8080/api/users/{{id}}
Content-Type: application/json

{
  "nickname": "{{currentNickname}}",
  "phoneNumber": "{{currentPhoneNumber}}",
  "street": "newStreet",
  "city": "{{currentCity}}",
  "state": "{{currentState}}",
  "details": "{{currentDetails}}",
  "zipCode": "{{currentZipCode}}"
}

### 회원 정보 수정 (주소 - 도시)
PATCH http://localhost:8080/api/users/{{id}}
Content-Type: application/json

{
   "nickname": "{{currentNickname}}",
 "phoneNumber": "{{currentPhoneNumber}}",
  "street": "{{currentStreet}}",
  "city": "new_city",
  "state": "{{currentState}}",
  "details": "{{currentDetails}}",
  "zipCode": "{{currentZipCode}}"
}

### 회원 정보 수정 (주소 - 군/구/)
PATCH http://localhost:8080/api/users/{{id}}
Content-Type: application/json

{
  "nickname": "{{currentNickname}}",
  "phoneNumber": "{{currentPhoneNumber}}",
  "street": "{{currentStreet}}",
  "city": "{{currentCity}}",
  "state": "new_state",
  "details": "{{currentDetails}}",
  "zipCode": "{{currentZipCode}}"
}

### 회원 정보 수정 (주소 - 상세)
PATCH http://localhost:8080/api/users/{{id}}
Content-Type: application/json

{
  "nickname": "{{currentNickname}}",
  "phoneNumber": "{{currentPhoneNumber}}",
  "street": "{{currentStreet}}",
  "city": "{{currentCity}}",
  "state": "{{currentState}}",
  "details": "new_details",
  "zipCode": "{{currentZipCode}}"
}

### 회원 정보 수정 (주소 - 우편번호)
PATCH http://localhost:8080/api/users/{{id}}
Content-Type: application/json

{
  "nickname": "{{currentNickname}}",
  "phoneNumber": "{{currentPhoneNumber}}",
 "street": "{{currentStreet}}",
  "city": "{{currentCity}}",
  "state": "{{currentState}}",
  "details": "{{currentDetails}}",
  "zipCode": "new_zipcode"
}

### 프로필 이미지 수정
PATCH http://localhost:8080/api/users/{{id}}/images/{{currentImageId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="test.png"
Content-Type: image/png

< ./test.png