### 회원가입
POST http://localhost:8080/api/users
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="test.png"
Content-Type: image/png

< ./test.png
--WebAppBoundary
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "email": "email_c166bd3665aa",
  "password": "password_6eba937579b6",
  "phoneNumber": "phoneNumber_a461870f84fb",
  "street": "street_f42fa85a43a1",
  "zipCode": "zipCode_3f828ede8a5d",
  "state": "state_b33630e89d76",
  "city": "city_6232d43546ca",
  "details": "details_2de90f41ec58",
  "name": "name_435c00db2258",
  "nickname": "nickname_9ca5bcb1ad24"
}

> {%
    client.global.set("id", response.body.data.userId);
%}

### 회원 정보 조회
GET localhost:8080/api/users/{{id}}
